# Generated by Django 4.2.10 on 2024-02-28 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0006_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='horarioatendimento',
            name='disponivel',
            field=models.BooleanField(default=True),
        ),
    ]
