# Generated by Django 4.2.10 on 2024-03-05 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0007_horarioatendimento_disponivel'),
    ]

    operations = [
        migrations.AddField(
            model_name='profissional',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='imagens/'),
        ),
    ]
